from enum import Enum

class State(str, Enum):
    ASK_SEARCH_MODE = "ASK_SEARCH_MODE"
    ASK_DISTRICT = "ASK_DISTRICT"
    ASK_LOCATION = "ASK_LOCATION"
    ASK_RADIUS = "ASK_RADIUS"
    ASK_PRODUCT = "ASK_PRODUCT"
    QUERY_DB = "QUERY_DB"
    SHOW_RETAILERS = "SHOW_RETAILERS"
    POST_RESULTS = "POST_RESULTS"
    NO_RESULTS = "NO_RESULTS"
    END = "END"